#ifndef CHECKERSAI_TGUIMENUFORMPREPROCESS_H
#define CHECKERSAI_TGUIMENUFORMPREPROCESS_H

#include <string>
#include <regex>
#include "SfmlUtils.h"
#include "TextureResources.h"

const char *MENU_FORM_SCHEME = "Renderer.1 {\n"
                       "}\n"
                       "\n"
                       "Renderer.2 {\n"
                       "    TextColor = rgb(100, 100, 100);\n"
                       "    Texture = \"[BabyBlueTheme]\" Part(269, 40, 90, 60) Middle(30, 0, 30, 60) Smooth;\n"
                       "    TextureDisabled = None;\n"
                       "    TextureDown = \"[BabyBlueTheme]\" Part(177, 40, 90, 60) Middle(30, 0, 30, 60) Smooth;\n"
                       "    TextureDownFocused = None;\n"
                       "    TextureDownHover = None;\n"
                       "    TextureFocused = None;\n"
                       "    TextureHover = \"[BabyBlueTheme]\" Part(361, 40, 90, 60) Middle(30, 0, 30, 60) Smooth;\n"
                       "}\n"
                       "\n"
                       "Panel.main_panel {\n"
                       "    Size = (700, 600);\n"
                       "\n"
                       "    Renderer {\n"
                       "        BackgroundColor = #071725;\n"
                       "        TextureBackground = None;\n"
                       "    }\n"
                       "\n"
                       "    Group.difficulty_group {\n"
                       "        Position = (100, 230);\n"
                       "        Renderer = &1;\n"
                       "        Size = (490, 53.2609);\n"
                       "\n"
                       "        Slider.difficulty_slider {\n"
                       "            ChangeValueOnScroll = true;\n"
                       "            InvertedDirection = false;\n"
                       "            Maximum = 10;\n"
                       "            Minimum = 2;\n"
                       "            Position = (190, 20);\n"
                       "            Size = (280, 20);\n"
                       "            Step = 1;\n"
                       "            Value = 5;\n"
                       "\n"
                       "            Renderer {\n"
                       "                TextureThumb = \"[BabyBlueTheme]\" Part(84, 40, 17, 38) Smooth;\n"
                       "                TextureThumbHover = None;\n"
                       "                TextureTrack = \"[BabyBlueTheme]\" Part(38, 2, 30, 20) Middle(10, 0, 10, 20) Smooth;\n"
                       "                TextureTrackHover = None;\n"
                       "            }\n"
                       "        }\n"
                       "\n"
                       "        Label.difficulty_label {\n"
                       "            Position = (-5.10001, 3.4528);\n"
                       "            Size = (170.2, 46.5984);\n"
                       "            Text = \"Difficulty:\";\n"
                       "            TextSize = 30;\n"
                       "            VerticalAlignment = Center;\n"
                       "\n"
                       "            Renderer {\n"
                       "                TextColor = rgba(255, 255, 255, 215);\n"
                       "                TextStyle = Regular;\n"
                       "                TextureBackground = None;\n"
                       "\n"
                       "                Scrollbar {\n"
                       "                    ArrowBackgroundColor = rgba(160, 160, 160, 215);\n"
                       "                    ArrowBackgroundColorHover = rgba(170, 170, 170, 215);\n"
                       "                    ArrowColor = rgba(200, 200, 200, 215);\n"
                       "                    ArrowColorHover = rgba(225, 225, 225, 215);\n"
                       "                    ThumbColor = rgba(185, 185, 185, 215);\n"
                       "                    ThumbColorHover = rgba(195, 195, 195, 215);\n"
                       "                    TrackColor = rgba(160, 160, 160, 215);\n"
                       "                    TrackColorHover = rgba(170, 170, 170, 215);\n"
                       "                }\n"
                       "            }\n"
                       "        }\n"
                       "    }\n"
                       "\n"
                       "    Button.new_game_btn {\n"
                       "        MouseCursor = Hand;\n"
                       "        Position = (90, 427.586);\n"
                       "        Renderer = &2;\n"
                       "        Size = (238, 74.8276);\n"
                       "        Text = \"New Game\";\n"
                       "        TextSize = 30;\n"
                       "    }\n"
                       "\n"
                       "    Group.color_group {\n"
                       "        Position = (100, 310);\n"
                       "        Renderer = &1;\n"
                       "        Size = (490, 53.2609);\n"
                       "\n"
                       "        CheckBox.color_checkbox {\n"
                       "            Checked = true;\n"
                       "            MouseCursor = Hand;\n"
                       "            Position = (0, 10);\n"
                       "            Size = (30, 30);\n"
                       "            Text = \"White color\";\n"
                       "            TextSize = 30;\n"
                       "\n"
                       "            Renderer {\n"
                       "                TextColor = #FFFFFFD7;\n"
                       "                TextureChecked = \"[BabyBlueTheme]\" Part(48, 40, 34, 36) Smooth;\n"
                       "                TextureCheckedDisabled = None;\n"
                       "                TextureCheckedFocused = None;\n"
                       "                TextureCheckedHover = None;\n"
                       "                TextureUnchecked = \"[BabyBlueTheme]\" Part(381, 2, 31, 31) Smooth;\n"
                       "                TextureUncheckedDisabled = None;\n"
                       "                TextureUncheckedFocused = None;\n"
                       "                TextureUncheckedHover = None;\n"
                       "            }\n"
                       "        }\n"
                       "    }\n"
                       "\n"
                       "    Button.load_game_btn {\n"
                       "        MouseCursor = Hand;\n"
                       "        Position = (370, 427.586);\n"
                       "        Renderer = &2;\n"
                       "        Size = (238, 74.8276);\n"
                       "        Text = \"Load Game\";\n"
                       "        TextSize = 30;\n"
                       "    }\n"
                       "\n"
                       "    Label.level_label {\n"
                       "        HorizontalAlignment = Center;\n"
                       "        Position = (290, 190);\n"
                       "        Size = (277.2, 41.0014);\n"
                       "        Text = \"LEVEL 5\";\n"
                       "        TextSize = 26;\n"
                       "        VerticalAlignment = Center;\n"
                       "\n"
                       "        Renderer {\n"
                       "            TextColor = #FFD38D;\n"
                       "            TextStyle = Bold;\n"
                       "            TextureBackground = None;\n"
                       "\n"
                       "            Scrollbar {\n"
                       "                TextureArrowDown = \"[BabyBlueTheme]\" Part(20, 2, 16, 16) Smooth;\n"
                       "                TextureArrowUp = \"[BabyBlueTheme]\" Part(2, 2, 16, 16) Smooth;\n"
                       "                TextureThumb = \"[BabyBlueTheme]\" Part(414, 2, 16, 32) Smooth;\n"
                       "                TextureTrack = \"[BabyBlueTheme]\" Part(432, 2, 16, 32) Smooth;\n"
                       "            }\n"
                       "        }\n"
                       "    }\n"
                       "}\n"
                       "\n"
                       "Label.title_label {\n"
                       "    HorizontalAlignment = Center;\n"
                       "    Size = (698, 184.289);\n"
                       "    Text = \"Super Checkers\";\n"
                       "    TextSize = 60;\n"
                       "    VerticalAlignment = Center;\n"
                       "\n"
                       "    Renderer {\n"
                       "        BorderColor = black;\n"
                       "        TextColor = #F8FEFFD7;\n"
                       "        TextStyle = Bold;\n"
                       "        TextureBackground = None;\n"
                       "\n"
                       "        Scrollbar {\n"
                       "            ArrowBackgroundColor = rgba(160, 160, 160, 215);\n"
                       "            ArrowBackgroundColorHover = rgba(170, 170, 170, 215);\n"
                       "            ArrowColor = rgba(200, 200, 200, 215);\n"
                       "            ArrowColorHover = rgba(225, 225, 225, 215);\n"
                       "            ThumbColor = rgba(185, 185, 185, 215);\n"
                       "            ThumbColorHover = rgba(195, 195, 195, 215);\n"
                       "            TrackColor = rgba(160, 160, 160, 215);\n"
                       "            TrackColorHover = rgba(170, 170, 170, 215);\n"
                       "        }\n"
                       "    }\n"
                       "}";

std::string gen_menu_form(){
    std::string theme_png_path = write_to_temp("babybluetheme.png", BABYBLUETHEME_PNG, BABYBLUETHEME_PNG_SIZE);
    std::string s = replace_all(MENU_FORM_SCHEME, "[BabyBlueTheme]", theme_png_path);
    return s;
}
#endif //CHECKERSAI_TGUIMENUFORMPREPROCESS_H
